version: '2'

services:
  streaming-spark-master:
    container_name: ${SPARK_MASTER_CONTAINER_NAME}
    hostname: ${SPARK_MASTER_HOST_NAME}
    image: streaming/spark
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ../spark-scripts:/spark-scripts
      - ../scripts:/scripts
    ports:
      - ${SPARK_MASTER_UI}:8080
      - ${SPARK_MASTER_PORT}:7077

  streaming-spark-worker-1:
    &worker_default
    container_name: ${SPARK_WORKER_CONTAINER_NAME}-1
    image: streaming/spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://${SPARK_MASTER_HOST_NAME}:${SPARK_MASTER_PORT}
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ../spark-scripts:/spark-scripts
      - ../scripts:/scripts
    depends_on:
      - streaming-spark-master

networks:
  default:
    name: streaming-network
    external: true
